services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    container_name: test-project-db-1
    env_file: ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db:/var/lib/postgresql/data
